[package]
name = "hello_web"
version = "0.1.0"
authors = ["Guillaume Galy <guillaume.galy@fabernovel.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
